"""Document engine — server-side report generation for the hosted app."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any, Dict, Optional

from ..ecosystem_laws import runtime_status
from ..network import get_network
from ..platform import platform_status
from ..receipts import seal
from .base import CloudEngine
from .chain_engine import ChainEngine
from .gas_engine import GasEngine
from .index_engine import IndexEngine

_ROOT = Path(__file__).resolve().parents[3]
_DOCS = _ROOT / "receipts" / "cloud_docs"
_DOCS.mkdir(parents=True, exist_ok=True)


class DocEngine(CloudEngine):
    id = "docs"
    name = "Document Engine"
    kind = "export"
    description = "Generate markdown ops/security/research reports on the server; download via API"
    requires_chain = False

    def run(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        p = params or {}
        kind = (p.get("kind") or "ops").lower()
        network = p.get("network") or "monad-testnet"
        net = get_network(network)
        ts = time.strftime("%Y-%m-%dT%H-%M-%SZ", time.gmtime())

        if kind == "research":
            from .research_engine import ResearchEngine

            res = ResearchEngine().run(
                {"query": p.get("query") or "Monad vault and gas", "network": network}
            )
            body = _md_research(res.get("brief") or {}, network)
            title = "cloud-research"
        elif kind == "gas":
            gas = GasEngine().run({"network": network, "estimated_gas": p.get("estimated_gas") or 80_000})
            body = _md_gas(gas, network)
            title = "cloud-gas"
        elif kind == "chain":
            chain = ChainEngine().run({"network": network, "op": "pulse", "address": p.get("address")})
            body = _md_chain(chain)
            title = "cloud-chain"
        else:
            plat = platform_status(network)
            idx = IndexEngine().run({"op": "all"})
            laws = runtime_status()
            body = _md_ops(plat, idx, laws, net)
            title = "cloud-ops"

        fname = f"{title}-{ts}.md"
        path = _DOCS / fname
        path.write_text(body, encoding="utf-8")
        seal("cloud.docs", {"kind": kind, "file": fname, "bytes": len(body)})
        return {
            "ok": True,
            "kind": kind,
            "filename": fname,
            "path": str(path),
            "bytes": len(body),
            "markdown": body,
            "download": f"/engines/docs/download/{fname}",
            "locality": "cloud",
        }


def _md_ops(plat: dict, idx: dict, laws: dict, net: dict) -> str:
    lines = [
        f"# THESIS Cloud Ops Report",
        "",
        f"**Network:** {net.get('id')} · chain {net.get('chain_id')}",
        f"**RPC:** {net.get('rpc')}",
        f"**Product:** {plat.get('product')} v{plat.get('version')}",
        "",
        "## Kernel",
        "",
        f"- Primitives OK: {plat.get('kernel', {}).get('primitives_ok')}/{plat.get('kernel', {}).get('primitives_total')}",
        f"- Apps: {plat.get('apps', {}).get('total')} (fp {plat.get('apps', {}).get('first_party_count')}, forged {plat.get('apps', {}).get('forged_count')})",
        f"- Laws: {laws.get('law_count')}",
        "",
        "## Index",
        "",
        f"- Packages: {idx.get('projects', {}).get('count')}",
        f"- Protocols: {idx.get('protocols', {}).get('count')}",
        f"- Vault: {idx.get('deployment', {}).get('vault') or 'not recorded'}",
        f"- Receipt tip: `{idx.get('receipts', {}).get('tip')}`",
        "",
        "## Doctrine",
        "",
        plat.get("doctrine") or "",
        "",
        "*Generated by cloud Document Engine · hosted web app*",
    ]
    return "\n".join(lines)


def _md_gas(gas: dict, network: str) -> str:
    return "\n".join(
        [
            "# THESIS Cloud Gas Report",
            "",
            f"**Network:** {network}",
            f"**Doctrine:** {gas.get('doctrine')}",
            f"**Estimated:** {gas.get('estimated_gas')}",
            f"**Recommended limit:** {gas.get('recommended_gas_limit')}",
            f"**Live gwei:** {gas.get('live_gas_price_gwei')}",
            f"**Est cost MON:** {gas.get('est_cost_at_recommended_mon')}",
            f"**Coach:** {(gas.get('coach') or {}).get('title')} — {(gas.get('coach') or {}).get('body')}",
            "",
            f"Laws: {', '.join(gas.get('laws') or [])}",
        ]
    )


def _md_chain(chain: dict) -> str:
    return "\n".join(
        [
            "# THESIS Cloud Chain Pulse",
            "",
            f"**OK:** {chain.get('ok')} · match={chain.get('chain_match')}",
            f"**Chain:** expected {chain.get('expected_chain_id')} observed {chain.get('observed_chain_id')}",
            f"**Block:** {chain.get('block_number')}",
            f"**Gas gwei:** {chain.get('gas_price_gwei')}",
            f"**RPC:** {chain.get('rpc')}",
            f"**Note:** {chain.get('note')}",
            "",
            json.dumps({k: chain.get(k) for k in ("address", "balance_mon", "has_code") if k in chain}, indent=2),
        ]
    )


def _md_research(brief: dict, network: str) -> str:
    lines = [
        "# THESIS Cloud Research Brief",
        "",
        f"**Query:** {brief.get('query')}",
        f"**Network:** {network}",
        f"**Summary:** {brief.get('summary')}",
        "",
        "## Insights",
        "",
    ]
    for i in brief.get("insights") or []:
        lines.append(f"### {i.get('title')}")
        lines.append(i.get("body") or "")
        lines.append(f"Laws: {', '.join(i.get('laws') or [])}")
        lines.append("")
    lines.append("## Chain")
    lines.append(json.dumps(brief.get("chain") or {}, indent=2))
    lines.append("")
    lines.append("## Desk")
    lines.append(json.dumps(brief.get("desk") or {}, indent=2))
    return "\n".join(lines)
