services:
  - type: web
    name: monad-engine
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8043
      - key: THESIS_CORS
        value: "*"
