"""CODEX source package generation — multi-file project artifacts."""

from __future__ import annotations

import json
from typing import Any, Dict

from .models import BuildManifest


def generate_package(manifest: BuildManifest) -> Dict[str, str]:
    """Return path → file content for a full generated project package."""
    m = manifest
    policy = m.policy
    net = m.network
    chain = m.chain_id
    protocols_json = json.dumps(
        [p.model_dump(mode="json") for p in m.protocols], indent=2
    )
    policy_json = json.dumps(policy.model_dump(mode="json"), indent=2)

    files: Dict[str, str] = {}

    files["README.md"] = f"""# {m.name}

> Generated by THESIS Forge · manifest `{m.manifest_hash[:16]}…`

## Objective

{m.objective}

## Network

- Network: `{net}`
- Chain ID: `{chain}`
- Primary contract: **SovereignVault**

## Doctrine

{m.doctrine}

## Quick start

```bash
# API already running in monorepo; contracts:
cd contracts
forge test
# deploy (WSL + funded key):
export PRIVATE_KEY=0x…
./scripts/deploy.sh testnet
```

## Lawbook

```json
{policy_json}
```

## Protocols selected

```json
{protocols_json}
```
"""

    files["manifest.json"] = json.dumps(m.model_dump(mode="json"), indent=2)

    files["policy/lawbook.json"] = policy_json

    files["contracts/PolicySnapshot.sol"] = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title PolicySnapshot — documentation contract generated by THESIS STUDIO
/// @notice Mirrors off-chain lawbook for human/agent review. Deploy PolicyKernel on-chain.
library PolicySnapshot {{
    uint16 internal constant MAX_SLIPPAGE_BPS = {policy.max_slippage_bps};
    uint16 internal constant MAX_PROTOCOL_EXPOSURE_BPS = {policy.max_protocol_exposure_bps};
    uint16 internal constant MIN_LIQUID_RESERVE_BPS = {policy.min_liquid_reserve_bps};
    uint32 internal constant MAX_LEVERAGE_BPS = {policy.max_leverage_bps};
    // max action value is float off-chain; encode as wei-scale comment
    // max_action_value ≈ {policy.max_action_value}
}}
"""

    files["contracts/IThesisVault.sol"] = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

interface IThesisVault {
    function execute(address target, uint256 value, uint256 slippageBps, bytes calldata data)
        external
        returns (bytes memory);
    function owner() external view returns (address);
}
"""

    cats = ", ".join(f'"{c.value}"' for c in policy.allowed_categories)
    files["src/config.ts"] = f"""/** THESIS generated network + policy config */
export const THESIS_CONFIG = {{
  projectId: {json.dumps(m.project_id)},
  name: {json.dumps(m.name)},
  network: {json.dumps(net)},
  chainId: {chain},
  manifestHash: {json.dumps(m.manifest_hash)},
  policy: {{
    maxSlippageBps: {policy.max_slippage_bps},
    maxProtocolExposureBps: {policy.max_protocol_exposure_bps},
    minLiquidReserveBps: {policy.min_liquid_reserve_bps},
    maxLeverageBps: {policy.max_leverage_bps},
    maxActionValue: {policy.max_action_value},
    allowedCategories: [{cats}] as const,
  }},
  primaryContract: "SovereignVault",
  doctrine: {json.dumps(m.doctrine)},
}} as const;
"""

    files["src/hooks/usePolicyGate.ts"] = """/** Client-side mirror of NOMOS checks (UI only — chain is source of truth). */
export type Plan = {
  slippageBps: number;
  exposureBps: number;
  reserveBps: number;
  leverageBps: number;
  value: number;
  category: string;
};

export type Lawbook = {
  maxSlippageBps: number;
  maxProtocolExposureBps: number;
  minLiquidReserveBps: number;
  maxLeverageBps: number;
  maxActionValue: number;
  allowedCategories: readonly string[];
};

export function evaluatePlan(plan: Plan, law: Lawbook) {
  const violations: string[] = [];
  if (!law.allowedCategories.includes(plan.category)) violations.push("category-not-allowed");
  if (plan.slippageBps > law.maxSlippageBps) violations.push("slippage-limit");
  if (plan.exposureBps > law.maxProtocolExposureBps) violations.push("protocol-exposure-limit");
  if (plan.reserveBps < law.minLiquidReserveBps) violations.push("liquid-reserve-limit");
  if (plan.leverageBps > law.maxLeverageBps) violations.push("leverage-limit");
  if (plan.value > law.maxActionValue) violations.push("action-value-limit");
  return { accepted: violations.length === 0, violations };
}
"""

    files["scripts/deploy-commands.sh"] = f"""#!/usr/bin/env bash
# Generated deploy helpers for {m.name}
set -euo pipefail
export MONAD_RPC="{m.deploy_plan.get('rpc', 'https://testnet-rpc.monad.xyz')}"
echo "chain_id={chain}"
echo "Run from monorepo root:"
echo "  ./scripts/deploy.sh {'mainnet' if chain == 143 else 'testnet'}"
echo "Verify:"
echo "  {m.deploy_plan.get('commands', {}).get('verify_template', 'forge verify-contract ...')}"
"""

    files["docs/AGENT.md"] = f"""# Agent operating manual — {m.name}

## Hard constraints (must not violate)

1. Never propose slippage_bps > {policy.max_slippage_bps}
2. Never propose exposure > {policy.max_protocol_exposure_bps} bps
3. Never drop liquid reserve below {policy.min_liquid_reserve_bps} bps
4. Never exceed leverage {policy.max_leverage_bps} bps
5. Never exceed action value {policy.max_action_value}
6. Categories limited to: {', '.join(c.value for c in policy.allowed_categories)}
7. Only use protocols listed in manifest.json
8. Seal a receipt for every material act

## Propose → evaluate → execute

1. Draft Action JSON
2. POST /evaluate or /arena
3. If REJECTED, explain violations to the user — do not retry with same violations
4. If ACCEPTED, user must explicitly authorize on-chain execute
"""

    files["tests/policy_mirror.test.json"] = json.dumps(
        {
            "cases": [
                {
                    "name": "lawful",
                    "expect": "accept",
                    "action": {
                        "slippage_bps": min(10, policy.max_slippage_bps),
                        "value": min(50, policy.max_action_value),
                    },
                },
                {
                    "name": "slippage-breach",
                    "expect": "reject",
                    "action": {"slippage_bps": policy.max_slippage_bps + 100},
                },
            ]
        },
        indent=2,
    )

    files[".thesis/meta.json"] = json.dumps(
        {
            "generator": "thesis-forge",
            "version": "0.3.0",
            "project_id": m.project_id,
            "manifest_hash": m.manifest_hash,
            "files": list(files.keys()) + [".thesis/meta.json"],
        },
        indent=2,
    )

    return files


def package_stats(files: Dict[str, str]) -> Dict[str, Any]:
    return {
        "n_files": len(files),
        "total_bytes": sum(len(v.encode("utf-8")) for v in files.values()),
        "paths": sorted(files.keys()),
    }
