"""20 use cases — product asks mapped for API + UI."""

from __future__ import annotations

from typing import Any, Dict, List

USE_CASES: List[Dict[str, Any]] = [
    {
        "id": 1,
        "title": "Morning seatbelt",
        "ask": "Personal problem — tab hell / re-check bots",
        "who": "Solo DeFi operator",
        "pain": "20 minutes re-checking bots, gas, and balances every morning",
        "do": "Click sticky ▶ RUN SYSTEM; read system result chips",
        "tabs": ["live", "home", "cloud"],
        "api": ["POST /system/run", "GET /system"],
        "laws": ["intel.teach-on-action", "monad.gas-bills-limit"],
    },
    {
        "id": 2,
        "title": "Fat gas limit avoided",
        "ask": "Monad gas best practices (pay the limit)",
        "who": "Anyone sending txs on Monad",
        "pain": "2× gas buffers burn MON because users pay gas_limit",
        "do": "CLOUD → gas engine; POLYGLOT → Julia gas; LOCAL AI gas lesson",
        "tabs": ["cloud", "poly", "local"],
        "api": ["POST /engines/gas/run", "POST /polyglot/run"],
        "laws": ["monad.gas-bills-limit", "monad.native-transfer-gas"],
    },
    {
        "id": 3,
        "title": "Celebrate a REJECT",
        "ask": "Agents need brakes — reject is a feature",
        "who": "User funding agent strategies",
        "pain": "Soft UIs accept degen leverage / perps",
        "do": "Arena or RUN SYSTEM → DESK reject list with reasons",
        "tabs": ["desk", "live", "nomos"],
        "api": ["POST /desk/arena", "POST /system/run"],
        "laws": ["sys.nomos-veto", "intel.explain-rejects"],
    },
    {
        "id": 4,
        "title": "Vault route before sign",
        "ask": "Onchain vault / no silent broadcast",
        "who": "Wallet owner",
        "pain": "Execute without simulation or policy gate",
        "do": "DESK vault route sim after accepted ticket",
        "tabs": ["desk", "codex"],
        "api": ["POST /desk/vault-route/{id}"],
        "laws": ["exec.no-silent-broadcast", "sys.mandatory-simulation"],
    },
    {
        "id": 5,
        "title": "Link wallet public-only",
        "ask": "Wallets without key theft",
        "who": "Phantom/MetaMask user",
        "pain": "Apps/AI requesting seeds",
        "do": "Use bar Link wallet → sync twins",
        "tabs": ["ai"],
        "api": ["POST /wallets/link", "POST /wallets/sync-twins"],
        "laws": ["sys.no-real-keys", "sys.sandbox-first"],
    },
    {
        "id": 6,
        "title": "AI sandbox twins",
        "ask": "AI help without real capital custody",
        "who": "Automation-curious owner",
        "pain": "AI with exportable keys",
        "do": "AI NODE chat balances/gas — twins only",
        "tabs": ["ai"],
        "api": ["GET /ai", "POST /ai/chat"],
        "laws": ["sys.sandbox-first", "sys.no-real-keys"],
    },
    {
        "id": 7,
        "title": "Staff the DeFi company",
        "ask": "Miniature company OS not dashboard widgets",
        "who": "One-person desk",
        "pain": "Research/risk/exec/teach scattered",
        "do": "Staff company → HQ mission approve/reject",
        "tabs": ["hq", "live"],
        "api": ["POST /company/run", "POST /company/missions/{id}/act"],
        "laws": ["sys.owner-sovereign", "intel.compete-plans"],
    },
    {
        "id": 8,
        "title": "Personal constitution",
        "ask": "Owner laws (liquidity, no leverage)",
        "who": "Risk-conscious owner",
        "pain": "Apps ignore personal limits",
        "do": "HQ constitution; company run under dual stacks",
        "tabs": ["hq"],
        "api": ["GET/POST /company/constitution"],
        "laws": ["sys.nomos-veto", "proto.category-gate"],
    },
    {
        "id": 9,
        "title": "Teach as you operate",
        "ask": "Learn mid-action not abstract slides",
        "who": "Operator learning Monad DeFi",
        "pain": "Tutorials don't stick",
        "do": "LOCAL AI Teach lessons + PLATFORM law chips",
        "tabs": ["local", "live"],
        "api": ["GET /landing", "browser://local-ai/teach"],
        "laws": ["intel.teach-on-action"],
    },
    {
        "id": 10,
        "title": "Security gate on secrets",
        "ask": "Security monitoring + no key paste",
        "who": "Tired operator",
        "pain": "Accidental seed in chat",
        "do": "LOCAL AI scan / CLOUD security engine",
        "tabs": ["local", "cloud"],
        "api": ["POST /engines/security/run"],
        "laws": ["sys.no-real-keys"],
    },
    {
        "id": 11,
        "title": "Cloud research brief",
        "ask": "Hosted web app cloud engines",
        "who": "Hosted product user",
        "pain": "Manual RPC + doc hunting",
        "do": "CLOUD → research or pipeline",
        "tabs": ["cloud"],
        "api": ["POST /engines/research/run", "POST /engines/pipeline"],
        "laws": ["intel.no-hallucinated-apy"],
    },
    {
        "id": 12,
        "title": "Live Monad chain pulse",
        "ask": "Real chain / web app on their network",
        "who": "Builder on testnet",
        "pain": "Wrong chain or dead RPC",
        "do": "CLOUD → chain engine; CODEX probe RPC",
        "tabs": ["cloud", "codex"],
        "api": ["POST /engines/chain/run", "GET /rpc/probe"],
        "laws": ["monad.finality", "sys.adapter-honesty"],
    },
    {
        "id": 13,
        "title": "Julia Monte Carlo risk",
        "ask": "Lots of Julia embedded intelligence",
        "who": "Risk-aware owner",
        "pain": "No VaR before sizing",
        "do": "POLYGLOT → monte_carlo or mesh",
        "tabs": ["poly"],
        "api": ["POST /polyglot/run", "POST /polyglot/mesh"],
        "laws": ["sys.mandatory-simulation"],
    },
    {
        "id": 14,
        "title": "Julia spectral marks",
        "ask": "Julia spectral / intelligence features",
        "who": "Trader watching marks",
        "pain": "Flat price series",
        "do": "POLYGLOT → spectral",
        "tabs": ["poly"],
        "api": ["POST /polyglot/run {lang:julia,cmd:spectral}"],
        "laws": ["intel.no-hallucinated-apy"],
    },
    {
        "id": 15,
        "title": "Node agent ranking",
        "ask": "Agents + Node + lawful ranking",
        "who": "Multi-agent user",
        "pain": "Degen ranks first by return only",
        "do": "POLYGLOT → agent-rank; mesh winner",
        "tabs": ["poly", "desk"],
        "api": ["POST /polyglot/run {lang:node,cmd:agent-rank}"],
        "laws": ["sys.nomos-veto", "intel.compete-plans"],
    },
    {
        "id": 16,
        "title": "WebGPU + WASM local compute",
        "ask": "WebGPU, WASM embedded",
        "who": "Privacy / offline user",
        "pain": "All intel needs cloud GPU",
        "do": "POLYGLOT probes WebGPU + WASM; LOCAL AI embeddings",
        "tabs": ["poly", "local"],
        "api": ["browser WebGPU/WASM", "LOCAL AI"],
        "laws": ["sys.sandbox-first"],
    },
    {
        "id": 17,
        "title": "Custom offline Transformers models",
        "ask": "Custom models Transformers.js",
        "who": "Prod team blocking HF Hub",
        "pain": "Forced remote model download",
        "do": "LOCAL AI Models → Offline preset + /models/ + /wasm/",
        "tabs": ["local"],
        "api": ["browser transformers env"],
        "laws": ["sys.no-real-keys"],
    },
    {
        "id": 18,
        "title": "PDF / Excel audit pack",
        "ask": "Document generation for ops/judges",
        "who": "Operator or Spark judge",
        "pain": "Screenshots only",
        "do": "LOCAL AI Export PDF/Excel; CLOUD docs engine",
        "tabs": ["local", "cloud", "judge"],
        "api": ["POST /engines/docs/run", "browser jspdf/xlsx"],
        "laws": ["sys.receipt-every-material-act"],
    },
    {
        "id": 19,
        "title": "Security extension package",
        "ask": "Packaged extension downloads",
        "who": "Browser-all-day user",
        "pain": "Scan only inside app",
        "do": "LOCAL AI → Download extension ZIP → load unpacked",
        "tabs": ["local"],
        "api": ["browser extension zip"],
        "laws": ["sys.no-real-keys", "sys.owner-sovereign"],
    },
    {
        "id": 20,
        "title": "Forge installable package",
        "ask": "Real apps in workspace not toast demos",
        "who": "Builder",
        "pain": "One-off scripts",
        "do": "STUDIO pipeline → IDE package → PLATFORM registry",
        "tabs": ["studio", "ide", "live"],
        "api": ["POST /pipeline", "GET /workspace/projects"],
        "laws": ["sys.receipt-every-material-act", "sys.adapter-honesty"],
    },
]


def use_cases_payload() -> Dict[str, Any]:
    return {
        "schema": "thesis.use_cases.v1",
        "count": len(USE_CASES),
        "hackathon": {
            "name": "Spark · Build Anything",
            "prompt": "Build Anything onchain that solves a personal problem",
            "url": "https://buildanything.so/hackathons/spark",
        },
        "use_cases": USE_CASES,
        "demo_order": [1, 3, 4, 7, 2, 12, 13, 15, 9, 18],
        "how_to_use_in_app": [
            "Open PLATFORM — sticky ▶ RUN SYSTEM covers 1,3,4,7,13",
            "Open each tab listed in a use case and press the named control",
            "PROOF tab for judge scorecard; USE CASES tab for this list",
        ],
    }


def use_case_by_id(uc_id: int) -> Dict[str, Any] | None:
    for u in USE_CASES:
        if u["id"] == uc_id:
            return u
    return None
