import { pgTable, serial, text, timestamp, boolean } from "drizzle-orm/pg-core";

/**
 * Wallets generated by MonadBuilder+ — for non-crypto users who don't have MetaMask,
 * for AI agents that hold and transact MON autonomously, and for learners who earn
 * rewards by completing education modules.
 *
 * Private keys are stored as plaintext here for hackathon/testnet purposes.
 * In production: encrypt with KMS before storage.
 */
export const walletsTable = pgTable("wallets", {
  id:          serial("id").primaryKey(),
  label:       text("label").notNull(),               // "Alice's Wallet", "THESIS Agent", "Learner #42"
  role:        text("role").notNull().default("user"), // "user" | "agent" | "learner" | "educator"
  address:     text("address").notNull().unique(),
  privateKey:  text("private_key").notNull(),
  mnemonic:    text("mnemonic"),                       // optional — shown to user once for backup
  balanceCache: text("balance_cache"),                 // last known MON balance (string, wei)
  balanceFetchedAt: timestamp("balance_fetched_at"),
  notes:       text("notes"),                          // free-form metadata
  createdAt:   timestamp("created_at").notNull().defaultNow(),
  updatedAt:   timestamp("updated_at").notNull().defaultNow(),
});

export type Wallet    = typeof walletsTable.$inferSelect;
export type NewWallet = typeof walletsTable.$inferInsert;

/**
 * Education module progress — tracks which lessons a wallet address has completed
 * and whether a MON reward has been sent for that completion.
 */
export const educationProgressTable = pgTable("education_progress", {
  id:            serial("id").primaryKey(),
  walletAddress: text("wallet_address").notNull(),
  moduleId:      text("module_id").notNull(),   // e.g. "monad-101", "defi-basics", "dao-voting"
  moduleTitle:   text("module_title").notNull(),
  score:         text("score"),                  // quiz score, 0-100
  completed:     boolean("completed").notNull().default(false),
  rewardSent:    boolean("reward_sent").notNull().default(false),
  rewardTxHash:  text("reward_tx_hash"),
  rewardAmount:  text("reward_amount"),          // in MON (e.g. "0.1")
  completedAt:   timestamp("completed_at"),
  createdAt:     timestamp("created_at").notNull().defaultNow(),
});

export type EducationProgress    = typeof educationProgressTable.$inferSelect;
export type NewEducationProgress = typeof educationProgressTable.$inferInsert;
